---
title: "Answers to questions Biodiversity Facets tutorial"
author: "Matthias Grenié & Marten Winter"
date: "Monday July 5th 2021"
output:
  html_document:
    toc: yes
bibliography: bibliography.bib
editor_options:
  chunk_output_type: console
---

Here are answers regarding all the questions asked in the tutorial.

# Loading the data (Q1-Q6)

## Summarizing the data

* **Q1**: How many plots were sampled?
* **Q2**: How many species are there in the dataset?
* **Q3**: How many traits are available?
* **Q4**: How many of them are continuous? How many of them are discrete?
* **Q5**: What is the most numerous family among all observed species?
* **Q6**: What is the most numerous genus?


# Functional diversity (Q7-Q19)

## Computing Biomass-weighted mean traits per plot

* **Q7**: How would you describe the relationship between the different CWMs and forest loss?
* **Q8**: Can you test the correlation using the function `cor.test()` and does it support your previous statements?
* **Q9**: How would you describe the understorey vegetation changes with increasing forest loss?

## Building the functional space

* **Q10**: How does this observation compare to above description of the change of understorey vegetation along the forest loss gradient?
* **Q11**: Using the metadata available in the `README.txt` file, what is the meaning `pgf` column means?
* **Q12**: How do you interpret the PCoA results given your answer to the previous question?

## Computing functional diversity indices

* **Q13**: How would you describe the relationships between functional diversity and forest loss and road density?
* **Q14**: Using the plot generated by the code beneath how could you describe the relationships between the three different functional diversity indices we computed?
* **Q15**: How does the relationship between indices with species richness compare with the one observed with total biomass values? (You can use the function `cor.test()` if you want to test the association)

## Null modeling

* **Q16**: How would describe verbally the position of the observed value of FRic for site "a100f177r" compared to the null distribution?
* **Q17**: What the quantile of the observed FRic value in the end?
* **Q18**: Using the `subset()` function with the greater (or equal) than `>=` and the lower (or equal) than `<=`, can you determine how many sites show a significant deviation from the null observation? (absolute SES >= 2)
* **Q19**: Using similar code as used for observed values, what are the relationships between SES values and forest loss?

# Phylogenetic diversity (Q20-Q27)

## Getting the phylogenetic tree

* **Q20**: How many taxa are in the phylogenetic tree?
* **Q21**: How does this number compare to the number of taxa found in the dataset?

## Computing phylogenetic diversity indices

* **Q22**: What do you notice with the species names? Especially compared to the ones available in `species_traits`.
* **Q23**: What are the relationships between weighted and unweighted version of the MPD?
* **Q24**: What are the relationships between MPD and taxa richness? And with forest loss? Plot these relationships to visualize them and use the `cor.test()` function to validate your observations.

## Null modeling

* **Q25**: Explain what does the column `mpd.obs.z` means? How does this compare with the SES values we computed for functional diversity indices?
* **Q26**: How does the standardized value relates with taxa richness?
* **Q27**: What are the relationships between MPD values considering null models and forest loss? Visualize the relationships with the `plot()` function, validate your observations with the `cor.test()` function.

# Comparing facets (Q28)

* **Q28**: How are related are observed values of functional diversity and phylogenetic diversity? What about the SESs?

# Modelling the effect of logging (Q29-Q31)

## Single-predictor models

* **Q29**: How would you qualify the effect of forest loss on the taxa richness?
* **Q30**: With the same formula build similar models with the other predictors `roaddensprim` and `roaddistprim`. How do they compare with forest loss?

## Multi-predictors models

* **Q31**: What can you say about the effect of the disturbances on the different diversity metrics? What are the explanatory power of our models?
