---
title: Macroecology and Macroevolution under Global Changes - "Biodiversity facets in macro-space"
author: "Matthias Grenié & Marten Winter"
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This the first practical session in the course "Macroecology and Macroevolution under Global Change". This it the practical session companion to the lectures on biodiversity facets L2 and L3.

**Year**: 2021

**Instructors**: Matthias Grenié & Marten Winter

Contact us via Slack or email for any further questions.


## Goals

* Manipulate research open data;
* Learn how to compute functional diversity indices with `fundiversity` (load trait data, build a functional space, compute indices);
* Learn how to compute phylogenetic diversity indices with `ape` and `picante` (load phylogenetic tree, visualize phylogenetic tree, compute indices);
* Familiarize with null models;
* Know the difference between facets of functional and phylogenetic diversity indices;
* Visualize biodiversity facets on the map;
* Show the effect of logging in a tropical forest context on some biodiversity facets.

## How to use it?

1. **Online** It is accessible online at https://rekyt.github.io/biodiversity_facets_tutorial/ click on `Tutorial` in the navigation bar to access the tutorial.
1. **Online** if the website have issue you can access a similar version with the following command: https://htmlpreview.github.io/?https://github.com/Rekyt/biodiversity_facets_tutorial/blob/main/docs/index.html
1. **Offline** You can access open the `diversity_facets_tutorial.Rmd` file in RStudio to follow along.
1. **Offline** You can also open the `diversity_facets_tutorial.R` file in RStudio to get only the code to execute exactly the codes here.

## Data provenance

The data we'll be using throughout the tutorial comes from the following article: 

> Döbert, T.F., Webber, B.L., Sugau, J.B., Dickinson, K.J.M. and Didham, R.K. (2017), Logging increases the functional and phylogenetic dispersion of understorey plant communities in tropical lowland rain forest. J Ecol, 105: 1235-1245. https://doi.org/10.1111/1365-2745.12794

The data has been deposited on a open data repository called dryad with the following reference:

> Döbert, Timm F. et al. (2018), Data from: Logging increases the functional and phylogenetic dispersion of understorey plant communities in tropical lowland rainforest, Dryad, Dataset, https://doi.org/10.5061/dryad.f77p7

## Going Further

Other courses on biodiversity facets and potential interesting papers & tools:

* The [`FD`](https://cran.r-project.org/package=FD) package is the reference package to compute functional diversity indices.
* The [Modern concepts and methods in Macroecology and Biogeography](https://github.com/patrickweigelt/MCMMB/) course accessible with this link: http://htmlpreview.github.io/?https://github.com/patrickweigelt/MCMMB/blob/master/index.html.
* The following [Legras et al. 2018 paper](https://doi.org/10.1016/j.actao.2018.02.007) on functional diversity concepts.


## License

[CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/)
