on:
  push:
    paths:
      - "*.Rmd"

name: Render site

jobs:
  render:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          R -e 'install.packages(c("renv", "remotes"))'
          R -e 'renv::restore()'
          R -e 'remotes::install_cran("rmarkdown")'
      
      - name: Copy README.Rmd into index.Rmd
        run: |
          cp README.Rmd index.Rmd

      - name: Render site 
        run: |
          Rscript -e 'rmarkdown::render_site()'

      - name: Commit results
        run: |
          git pull origin
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit docs/ -m 'Re-build site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
